# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Get Curriculum ICS

on:
  workflow_dispatch:
    inputs:
      cookies:
        description: 'What you got from document.cookies, without quota'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Get current time
      uses: 1466587594/get-current-time@v2
      id: current-time
      with:
        format: YYYYMMDDTHHmmss
        utcOffset: "+08:00"

    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Generate ICS
      run: python curriculum.py
      env:
        cookies: "${{ github.event.inputs.cookies }}"

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "${{ steps.current-time.outputs.formattedTime }}"
        title: "Curriculum ICS"
        prerelease: true
        files: "curriculum.ics"